# Data Processing for Time Series (LSTM, MLP, Transformer, etc)

In [22]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [23]:
data = pd.read_csv('../../ml_data/train_data.csv')

In [24]:
data

time_begin  time_begin_traj  theta_x  theta_y  vel_x  vel_y  \
0            0.358            0.358    -4.94   -10.76    0.0    0.0   
1            0.421            0.421    -4.94   -10.76    0.0    0.0   
2            0.485            0.485    -4.94   -10.76    0.0    0.0   
3            0.548            0.548    -4.94   -10.76    0.0    0.0   
4            0.612            0.612    -4.94   -10.76    0.0    0.0   
...            ...              ...      ...      ...    ...    ...   
111936    2321.834          130.763     6.17   -20.73    0.0    0.0   
111937    2321.906          130.835     6.17   -20.73    0.0    0.0   
111938    2321.978          130.907     6.17   -20.73    0.0    0.0   
111939    2322.049          130.978     6.17   -20.73    0.0    0.0   
111940    2322.121          131.050     6.17   -20.73    0.0    0.0   

        X_throttle  Y_throttle  
0              0.0         0.0  
1              0.0         0.0  
2              0.0         0.0  
3              0.0         0.0  
4              0.0         0.0  
...            ...         ...  
111936       -10.0       -10.0  
111937       -10.0       -10.0  
111938       -10.0       -10.0  
111939       -10.0       -10.0  
111940       -10.0       -10.0  

[111941 rows x 8 columns]

In [25]:

data['dt'] = data['time_begin'].diff()
data['new_traj'] = np.abs(data['dt']) > 10
data['traj_num'] = data['new_traj'].cumsum().ffill().astype(int)
dfs = []
for _, group in data.groupby('traj_num'):
    group['delta_theta_x'] = group['theta_x'].diff().shift(-1)
    group['delta_theta_y'] = group['theta_y'].diff().shift(-1)
    group['delta_vel_x'] = group['vel_x'].diff().shift(-1)
    group['delta_vel_y'] = group['vel_y'].diff().shift(-1)
    group = group.dropna()
    dfs.append(group)

data = (pd.concat(dfs, ignore_index=True)
          .drop(columns=['new_traj',
                         'dt',
                         'traj_num']))
data

time_begin  time_begin_traj  theta_x  theta_y  vel_x  vel_y  \
0            0.421            0.421    -4.94   -10.76    0.0    0.0   
1            0.485            0.485    -4.94   -10.76    0.0    0.0   
2            0.548            0.548    -4.94   -10.76    0.0    0.0   
3            0.612            0.612    -4.94   -10.76    0.0    0.0   
4            0.804            0.804    -4.94   -10.76    0.0    0.0   
...            ...              ...      ...      ...    ...    ...   
111615    2321.763          130.692     6.17   -20.73    0.0    0.0   
111616    2321.834          130.763     6.17   -20.73    0.0    0.0   
111617    2321.906          130.835     6.17   -20.73    0.0    0.0   
111618    2321.978          130.907     6.17   -20.73    0.0    0.0   
111619    2322.049          130.978     6.17   -20.73    0.0    0.0   

        X_throttle  Y_throttle  delta_theta_x  delta_theta_y  delta_vel_x  \
0              0.0         0.0            0.0            0.0          0.0   
1              0.0         0.0            0.0            0.0          0.0   
2              0.0         0.0            0.0            0.0          0.0   
3              0.0         0.0            0.0            0.0          0.0   
4              0.0         0.0            0.0            0.0          0.0   
...            ...         ...            ...            ...          ...   
111615       -10.0       -10.0            0.0            0.0          0.0   
111616       -10.0       -10.0            0.0            0.0          0.0   
111617       -10.0       -10.0            0.0            0.0          0.0   
111618       -10.0       -10.0            0.0            0.0          0.0   
111619       -10.0       -10.0            0.0            0.0          0.0   

        delta_vel_y  
0               0.0  
1               0.0  
2               0.0  
3               0.0  
4               0.0  
...             ...  
111615          0.0  
111616          0.0  
111617          0.0  
111618          0.0  
111619          0.0  

[111620 rows x 12 columns]

In [26]:
data.describe()

time_begin  time_begin_traj        theta_x        theta_y  \
count  111620.000000    111620.000000  111620.000000  111620.000000   
mean      937.341524        36.329852      -0.245466       0.815183   
std       645.813800        44.644732      44.896663      45.915282   
min         0.349000         0.349000    -100.000000     -99.990000   
25%       338.526250         8.396750     -32.660000     -31.590000   
50%       888.482500        20.106500       0.910000      -1.560000   
75%      1456.665500        46.356250      31.460000      34.840000   
max      2495.546000       330.539000     100.000000      99.960000   

               vel_x          vel_y     X_throttle     Y_throttle  \
count  111620.000000  111620.000000  111620.000000  111620.000000   
mean        0.328204      -0.329811      -0.171322      -0.059953   
std        15.274926      16.199538       1.942320       2.046768   
min       -91.594203    -127.183099     -10.000000     -10.000000   
25%        -9.714286     -10.152818      -1.000000      -1.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         9.545455       9.411765       1.000000       1.000000   
max       109.545455     104.714286       9.000000      10.000000   

       delta_theta_x  delta_theta_y    delta_vel_x    delta_vel_y  
count  111620.000000  111620.000000  111620.000000  111620.000000  
mean        0.020522      -0.032068      -0.002469      -0.000682  
std         1.226271       1.294674       9.113204      10.680893  
min        -6.670000      -9.780000     -57.134109     -68.672546  
25%        -0.770000      -0.820000      -5.462963      -7.094415  
50%         0.000000       0.000000       0.000000       0.000000  
75%         0.750000       0.760000       5.555556       7.168702  
max         7.760000       7.700000      52.703286      61.678322

In [27]:
data[data['delta_theta_y'] < -50]

Empty DataFrame
Columns: [time_begin, time_begin_traj, theta_x, theta_y, vel_x, vel_y, X_throttle, Y_throttle, delta_theta_x, delta_theta_y, delta_vel_x, delta_vel_y]
Index: []

In [28]:
data_insp = data[['time_begin', 'time_begin_traj', 'theta_x', 'theta_y', 'vel_x', 'vel_y', 'delta_theta_x', 'delta_theta_y', 'delta_vel_x', 'delta_vel_y']]
data_insp.head(200)

time_begin  time_begin_traj  theta_x  theta_y      vel_x      vel_y  \
0         0.421            0.421    -4.94   -10.76   0.000000   0.000000   
1         0.485            0.485    -4.94   -10.76   0.000000   0.000000   
2         0.548            0.548    -4.94   -10.76   0.000000   0.000000   
3         0.612            0.612    -4.94   -10.76   0.000000   0.000000   
4         0.804            0.804    -4.94   -10.76   0.000000   0.000000   
..          ...              ...      ...      ...        ...        ...   
195      37.281            7.110   -34.69   -49.57 -17.101449 -15.362319   
196      37.351            7.180   -35.73   -51.06 -14.857143 -21.285714   
197      37.421            7.250   -36.45   -52.54 -10.285714 -21.142857   
198      37.490            7.319   -37.37   -54.00 -13.333333 -21.159420   
199      37.560            7.389   -38.63   -55.82 -18.000000 -26.000000   

     delta_theta_x  delta_theta_y  delta_vel_x  delta_vel_y  
0             0.00           0.00     0.000000     0.000000  
1             0.00           0.00     0.000000     0.000000  
2             0.00           0.00     0.000000     0.000000  
3             0.00           0.00     0.000000     0.000000  
4             0.00           0.00     0.000000     0.000000  
..             ...            ...          ...          ...  
195          -1.04          -1.49     2.244306    -5.923395  
196          -0.72          -1.48     4.571429     0.142857  
197          -0.92          -1.46    -3.047619    -0.016563  
198          -1.26          -1.82    -4.666667    -4.840580  
199          -1.13          -1.59     1.623188     2.956522  

[200 rows x 10 columns]

In [29]:
data_insp.loc[98600:98623]

time_begin  time_begin_traj  theta_x  theta_y      vel_x      vel_y  \
98600    1875.539            8.589    26.30    87.24  11.470588  14.117647   
98601    1875.606            8.656    27.21    88.28  13.582090  15.522388   
98602    1875.674            8.724    28.02    89.10  11.911765  12.058824   
98603    1875.741            8.791    28.02    89.87   0.000000  11.492537   
98604    1876.002            9.052    29.48    91.10   5.593870   4.712644   
98605    1876.112            9.162    32.00    92.84  22.909091  15.818182   
98606    1876.180            9.230    34.79    94.43  41.029412  23.382353   
98607    1876.247            9.297    36.62    95.54  27.313433  16.567164   
98608    1876.315            9.365    37.83    96.48  17.794118  13.823529   
98609    1876.382            9.432    38.88    97.34  15.671642  12.835821   
98610    1876.450            9.500    40.02    98.55  16.764706  17.794118   
98611    1876.517            9.567    41.39    99.61  20.447761  15.820896   
98612    1876.585            9.635    42.78    99.61  20.441176   0.000000   
98613    1876.653            9.703    43.95    99.61  17.205882   0.000000   
98614       0.354            0.354     0.35   -10.94   0.000000   0.000000   
98615       0.416            0.416     0.35   -10.94   0.000000   0.000000   
98616       0.479            0.479     0.35   -10.94   0.000000   0.000000   
98617       0.541            0.541     0.35   -10.94   0.000000   0.000000   
98618       0.603            0.603     0.35   -10.94   0.000000   0.000000   
98619       0.794            0.794     0.35   -10.94   0.000000   0.000000   
98620       0.899            0.899     0.85   -10.30   4.761905   6.095238   
98621       0.964            0.964     0.85   -10.30   0.000000   0.000000   
98622       1.028            1.028     0.85    -9.45   0.000000  13.281250   
98623       1.092            1.092     1.81    -9.45  15.000000   0.000000   

       delta_theta_x  delta_theta_y  delta_vel_x  delta_vel_y  
98600           0.91           1.04     2.111501     1.404741  
98601           0.81           0.82    -1.670325    -3.463565  
98602           0.00           0.77   -11.911765    -0.566286  
98603           1.46           1.23     5.593870    -6.779894  
98604           2.52           1.74    17.315221    11.105538  
98605           2.79           1.59    18.120321     7.564171  
98606           1.83           1.11   -13.715979    -6.815189  
98607           1.21           0.94    -9.519315    -2.743635  
98608           1.05           0.86    -2.122476    -0.987709  
98609           1.14           1.21     1.093064     4.958297  
98610           1.37           1.06     3.683055    -1.973222  
98611           1.39           0.00    -0.006585   -15.820896  
98612           1.17           0.00    -3.235294     0.000000  
98613           1.81           1.69   -10.297485     6.450382  
98614           0.00           0.00     0.000000     0.000000  
98615           0.00           0.00     0.000000     0.000000  
98616           0.00           0.00     0.000000     0.000000  
98617           0.00           0.00     0.000000     0.000000  
98618           0.00           0.00     0.000000     0.000000  
98619           0.50           0.64     4.761905     6.095238  
98620           0.00           0.00    -4.761905    -6.095238  
98621           0.00           0.85     0.000000    13.281250  
98622           0.96           0.00    15.000000   -13.281250  
98623           0.75           0.00    -3.095238     0.000000

In [30]:
seq_len = 50
pred_len = 2


In [31]:
input_data = data[['time_begin', 'time_begin_traj', 'theta_x', 'theta_y', 'X_throttle', 'Y_throttle']]
output_data = data[['delta_theta_x', 'delta_theta_y', 'delta_vel_x', 'delta_vel_y']]
input_data = input_data.values
output_data = output_data.values

In [32]:
# tiled_input_data = np.array([input_data[:seq_len]])
num_sequences = input_data.shape[0] - seq_len
tiled_input_data = np.array([input_data[i:i+seq_len] for i in range(num_sequences)])
tiled_input_data.shape

(111570, 50, 6)

In [33]:
output_data = output_data[seq_len-1:]
tiled_out_data = np.array([output_data[i:i+pred_len] for i in range(num_sequences)])

In [34]:
data.iloc[seq_len-1:2*seq_len]


time_begin  time_begin_traj  theta_x  theta_y      vel_x      vel_y  \
49       4.416            4.416     5.29   -14.60   0.000000   0.000000   
50       4.480            4.480     5.29   -14.08   0.000000   8.125000   
51       4.543            4.543     6.04   -14.08  11.904762   0.000000   
52       4.606            4.606     6.58   -14.08   8.571429   0.000000   
53       4.670            4.670     7.28   -14.08  10.937500   0.000000   
54       4.860            4.860     8.86   -14.08   8.315789   0.000000   
55       4.966            4.966    10.56   -14.08  16.037736   0.000000   
56       5.030            5.030    11.74   -13.49  18.437500   9.218750   
57       5.095            5.095    12.59   -13.49  13.076923   0.000000   
58       5.158            5.158    13.41   -13.49  13.015873   0.000000   
59       5.223            5.223    14.20   -13.49  12.153846   0.000000   
60       5.287            5.287    15.15   -13.49  14.843750   0.000000   
61       5.352            5.352    16.49   -12.92  20.615385   8.769231   
62       5.416            5.416    17.78   -12.92  20.156250   0.000000   
63       5.481            5.481    18.92   -12.92  17.538462   0.000000   
64       5.675            5.675    20.83   -12.92   9.845361   0.000000   
65       5.781            5.781    24.08   -12.92  30.660377   0.000000   
66       5.846            5.846    27.15   -12.17  47.230769  11.538462   
67       5.910            5.910    28.92   -12.17  27.656250   0.000000   
68       5.975            5.975    30.44   -12.17  23.384615   0.000000   
69       6.039            6.039    32.28   -12.17  28.750000   0.000000   
70       6.104            6.104    34.15   -12.17  28.769231   0.000000   
71       6.168            6.168    35.79   -12.17  25.625000   0.000000   
72       6.233            6.233    37.04   -12.17  19.230769   0.000000   
73       6.297            6.297    38.27   -12.17  19.218750   0.000000   
74       6.490            6.490    40.57   -12.17  11.917098   0.000000   
75       6.596            6.596    44.22   -12.17  34.433962   0.000000   
76       6.661            6.661    47.47   -12.17  50.000000   0.000000   
77       6.725            6.725    49.24   -12.17  27.656250   0.000000   
78       6.790            6.790    50.41   -11.41  18.000000  11.692308   
79       6.854            6.854    51.71   -11.41  20.312500   0.000000   
80       6.919            6.919    53.28   -11.41  24.153846   0.000000   
81       6.983            6.983    54.93   -11.41  25.781250   0.000000   
82       7.048            7.048    56.35   -11.41  21.846154   0.000000   
83       7.112            7.112    57.57   -11.41  19.062500   0.000000   
84       7.309            7.309    59.21   -11.41   8.324873   0.000000   
85       7.416            7.416    61.85   -11.41  24.672897   0.000000   
86       7.483            7.483    64.57   -11.41  40.597015   0.000000   
87       7.549            7.549    66.21   -11.41  24.848485   0.000000   
88       7.616            7.616    66.86   -11.93   9.701493  -7.761194   
89       7.683            7.683    66.86   -11.93   0.000000   0.000000   
90       7.749            7.749    68.54   -12.52  25.454545  -8.939394   
91       7.816            7.816    70.00   -12.52  21.791045   0.000000   
92       7.882            7.882    70.86   -13.08  13.030303  -8.484848   
93       7.949            7.949    71.51   -13.86   9.701493 -11.641791   
94       8.147            8.147    73.05   -14.62   7.777778  -3.838384   
95       8.257            8.257    75.51   -15.33  22.363636  -6.454545   
96       8.325            8.325    77.98   -16.03  36.323529 -10.294118   
97       8.392            8.392    79.49   -16.03  22.537313   0.000000   
98       8.460            8.460    79.49   -16.78   0.000000 -11.029412   
99       8.527            8.527    80.27   -16.78  11.641791   0.000000   

    X_throttle  Y_throttle  delta_theta_x  delta_theta_y  delta_vel_x  \
49         2.0         0.0    

In [7]:
from robo_limb_ml.utils.data_loader import DataLoader

data_loader = DataLoader('../../ml_data/train_data.csv',
                         batch_size=1024,
                         device='cpu',
                         pad=True)

for i in range(data_loader.n_batches):
    batch, lable, set_num = data_loader.get_batch()
    print(set_num)
    if set_num == 0 or set_num==1:
        print(batch[:, 0, 0])
    
    

Index(['time_begin', 'time_begin_traj', 'theta_x', 'theta_y', 'vel_x', 'vel_y',
       'X_throttle', 'Y_throttle', 'set_num', 'delta_theta_x', 'delta_theta_y',
       'delta_vel_x', 'delta_vel_y'],
      dtype='object')
0.0
tensor([  0.4210,   0.4850,   0.5480,  ..., 148.9370, 149.0040, 149.0700])
0.0
tensor([149.1370, 149.2030, 149.2700,  ..., 341.0060, 341.0720, 341.1390])
0.0
tensor([341.3690, 362.0210, 362.0860,  ..., 513.5480, 513.6170, 513.8580])
0.0
tensor([513.9710, 514.0410, 514.1120,  ..., 707.5980, 707.6660, 707.7350])
0.0
tensor([707.8040, 708.0510, 708.1600,  ..., 901.4290, 901.4970, 901.5660])
0.0
tensor([ 901.6360,  901.7050,  901.7750,  ..., 1097.0081, 1097.0760,
        1097.3350])
0.0
tensor([1097.4460, 1097.5150, 1097.5830,  ..., 1272.6040, 1272.6710,
        1272.7371])
0.0
tensor([1272.9890, 1273.0980, 1273.1639,  ..., 1468.9860, 1469.0560,
        1469.1250])
0.0
tensor([1469.3860, 1469.4980, 1469.5680,  ..., 1687.1730, 1687.2410,
        1687.5070])
0.0
tensor([1